name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  dry_run:
    env:
      github_token: ${{ secrets.GH_PAT }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: install deps
        run: npm ci

      - name: run script
        run: node index.js --ci -c stubs/config.mjs -s output.svg
